/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include "adc.h"
#include "switch.h"
#include "i2c_lcd.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{   int ret;
	char str[32];
	uint16_t val;
	SystemInit();
	ADC_Init();
	SwitchInit(SWITCH);

    ret = LcdInit();

    //UartInit(BAUD_9600);
	//UartPuts("DESD ADC Demo...\r\n");

	while(1){

		// ADC output on LCD when switch pressed
		if (ret){
			while(exti0_flag == 0)
				;
			val = ADC_GetValue();
			sprintf(str,"ADC=%d",val);
			LcdPuts(LCD_LINE1,str);
			DelayMs(1000);
			exti0_flag = 0;
		     }


		/*
		//ADC output on minicom using uart
		val = ADC_GetValue();
		sprintf(str, "ADC=%d\r\n", val);
		UartPuts(str);
		DelayMs(1000);
         */


		/*
		//Adc value disply on minicom on switch press

		while(exti0_flag == 0)
		    ;
		val = ADC_GetValue();
		sprintf(str,"ADC=%d\r\n",val);
		UartPuts(str);
		DelayMs(1000);
		exti0_flag=0;
        */

	}

	return 0;
}
