/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "lcd01.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
		LcdInit();
		LcdPuts(LCD_LINE1, "come and");
		LcdPuts(LCD_LINE2, "code me");
		for(int i=0; i<16 ;i++)
		{
		DelayMs (1000);
		LcdWrite(LCD_CMD, LCD_CUR_SHF);
		}
		LcdWrite(LCD_CMD, LCD_CLEAR);
		return 0;
	}
